@Arahk.ProjectManager.WebApi_HostAddress = https://localhost:7242

GET {{Arahk.ProjectManager.WebApi_HostAddress}}/project/
Accept: application/json

###

GET {{Arahk.ProjectManager.WebApi_HostAddress}}/project/2
Accept: application/json

###

POST {{Arahk.ProjectManager.WebApi_HostAddress}}/project
Content-Type: application/json

{
    "Name": "Project A",
    "Description": "This is sample project A",
    "StartDate": "2025-04-01T12:00:00",
    "EndDate": "2025-04-30T12:00:00"
}

###
PATCH {{Arahk.ProjectManager.WebApi_HostAddress}}/project
Content-Type: application/json

{
    "Id": 2,
    "Name": "Project A",
    "Description": "This is sample project A",
    "StartDate": "2025-04-01T12:00:00",
    "EndDate": "2025-04-30T12:00:00",
    "StatusId": 1
}

###
DELETE {{Arahk.ProjectManager.WebApi_HostAddress}}/project/1
Accept: application/json